### ISSUE TITLE
Remove usage of kernel32-sys crate

### ISSUE THREAD

**Issue by atouchet** [darfink/detour-rs#17]
kernel32-sys is no longer used with winapi 0.3: https://github.com/retep998/winapi-rs#should-i-still-use-those--sys-crates-such-as-kernel32-sys

**Comment by darfink** [comment]
Ah, thanks for acknowledging this! I'll push up a fix for it shortly :)

**Comment by darfink** [comment]
Fixed with https://github.com/darfink/detour-rs/commit/f2c3f4c5f4bbcb9b2c49a03f9843e06b6d55766a
