### ISSUE TITLE
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable

### ISSUE THREAD

**Issue by lustrc** [darfink/detour-rs#19]
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
  --> src\detours\statik.rs:69:6
   |
69 | impl<T: Function> StaticDetour<T> {
   |      ^
   |
   = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
   = help: add `#![feature(const_fn_trait_bound)]` to the crate attributes to enable

add  Did not resolve

**Comment by darfink** [comment]
Fixed by #20
