### ISSUE TITLE
`const_fn` fix is not released on crates.io

### ISSUE THREAD

**Issue by DrChat** [darfink/detour-rs#24]
Just a friendly heads up - I ran into a broken build when trying to include this crate in another project.
I see that it's fixed in 3b6f17a8b51ba5b37addc8c4361e5cfbe2875243 but that commit is unreleased on crates.

**Comment by vurvdev** [comment]
Just ran into this 👍

**Comment by darfink** [comment]
Version on crates.io has been updated
